name: fing-watch deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      
      - name: Create data-refresh env file.
        run: |
          touch ./data-refresh/.env
          echo TMDB_API_KEY=${{ secrets.TMDB_API_KEY }} >> ./data-refresh/.env
          echo GORSE_ENTRY_POINT=${{ secrets.GORSE_SERVICE }} >> ./data-refresh/.env
          echo TYPESENSE=${{ secrets.TYPESENSE_SERVICE }} >> ./data-refresh/.env
          echo TYPESENSE_KEY=${{ secrets.TYPESENSE_KEY }} >> ./data-refresh/.env
          cat ./data-refresh/.env
      - name: Create flask env file.
        run: |
          touch ./backend/.env
          echo TMDB_API_KEY=${{ secrets.TMDB_API_KEY }} >> ./backend/.env
          echo GORSE_SERVICE=${{ secrets.GORSE_SERVICE }} >> ./backend/.env
          echo MONGO_DB=${{ secrets.MONGO_CONNECTION_URI }} >> ./backend/.env
          echo TYPESENSE=${{ secrets.TYPESENSE_SERVICE }} >> ./backend/.env
          echo TYPESENSE_KEY=${{ secrets.TYPESENSE_KEY }} >> ./backend/.env
          echo JWT_ENCODING_KEY=${{ secrets.JWT_ENCODING_KEY }} >> ./backend/.env
          echo TOKEN_VALIDITY=${{ secrets.JWT_TOKEN_VALIDITY }} >> ./backend/.env
          echo USERS_DB=${{ vars.DATABASE_NAME }} >> ./backend/.env
          echo USERS_COLLECTION=${{ vars.USERS_COLLECTION }} >> ./backend/.env
          cat ./backend/.env
      - name: Create next env file.
        run: |
          touch ./frontend/.env.local
          echo NEXT_PUBLIC_SERVER_API_URL=${{ vars.NEXT_PUBLIC_SERVER_API_URL }} >> ./frontend/.env.local
          echo NEXT_IMAGE_BASE_URL=${{ vars.NEXT_IMAGE_BASE_URL }} >> ./frontend/.env.local
          cat ./frontend/.env.local
      
      - name: Docker compose up.
        run: docker-compose up -d --build